apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
        - name: email
          image: nurettinsenbackend/email
          env:
            - name: PORT
              value: "4000"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: rcting
            - name: MAIL_HOST
              value: "smtp.office365.com"
            - name: USER_MAIL_AUTH
              value: "recep.mut@bestnet.com.tr"
            - name: USER_MAIL_PASSWORD
              value: "Fub38056"

---
apiVersion: v1
kind: Service
metadata:
  name: email-srv
spec:
  selector:
    app: email
  ports:
    - name: email
      protocol: TCP
      port: 4000
      targetPort: 4000
