apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-postgres-pv
  labels:
    app: db-postgres
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "hostpath"
  hostPath:
    path: /mnt/data
