apiVersion: apps/v1
kind: Deployment
metadata:
  name: userct-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userct
  template:
    metadata:
      labels:
        app: userct
    spec:
      containers:
        - name: userct
          image: nurettinsenbackend/userct
          env:
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "3000"
            - name: AUTH_HOST
              value: "rct.dev"
            - name: DB_NAME
              value: postgres
            - name: DB_HOST
              value: db-postgres-srv
            - name: DB_PASS
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: JWT_EXPIRES_IN
              value: "1m"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: rcting
---
apiVersion: v1
kind: Service
metadata:
  name: userct-srv
spec:
  selector:
    app: userct
  ports:
    - name: userct
      protocol: TCP
      port: 3000
      targetPort: 3000
